<a href="https://colab.research.google.com/github/Mr-rudra-narayan-sahu/assessment/blob/main/lab4lmpLibraries13.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
!git clone https://github.com/Mr-rudra-narayan-sahu/assessment.git
!git remote add origin https://github.com/Mr-rudra-narayan-sahu/assessment.git
!git branch -M main
!git push -u origin main

Cloning into 'assessment'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (24/24), done.
remote: Total 25 (delta 8), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (25/25), 10.89 MiB | 12.41 MiB/s, done.
Resolving deltas: 100% (8/8), done.
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git


In [10]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator # Import ImageDataGenerator from tensorflow.keras
from tensorflow.keras.preprocessing import image
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import PIL.Image as Image
from skimage import io
#Read an image file
url="https://iiif.lib.ncsu.edu/iiif/0052574/full/800,/0/default.jpg"
imge = io.imread(url) # open an image
# Load the image
img = imge #load the image
# Convert image to numpy array
x = image.img_to_array(img)
# Reshape the image to (1, img_width, img_height, channels)
x = np.expand_dims(x, axis=0)
print(x)
# Create an instance of ImageDataGenerator and specify augmentation parameters
datagen = ImageDataGenerator(
    rotation_range=20,
    width_shift_range=0.2,
    height_shift_range=0.2,
    shear_range=0.2,
    zoom_range=0.2,
    horizontal_flip=True,
    fill_mode='nearest')
# Generate augmented images
i = 0
for batch in datagen.flow(x, batch_size=1, save_to_dir='/content/sample_data', save_prefix='aug', save_format='png'):
    # Indented block within the for loop
    i += 1
    if i > 40:
        break
'''
The first step is to load an image using image.load_img() and then convert it to a
array. Next, an instance of ImageDataGenerator is created with several augmentation
parame Finally, datagen.flow() is used to generate augmented images. The flow()method tak The for loop then iterates through the batches of augmented images
# generated by flo
# Overall, this code can be useful for generating additional training data for comput
'''

[[[[ 86. 152. 210.]
   [ 90. 155. 213.]
   [ 92. 157. 215.]
   ...
   [ 50. 115. 181.]
   [ 47. 115. 180.]
   [ 45. 113. 178.]]

  [[ 89. 154. 212.]
   [ 90. 155. 213.]
   [ 90. 155. 213.]
   ...
   [ 49. 114. 178.]
   [ 48. 113. 177.]
   [ 45. 113. 178.]]

  [[ 88. 153. 211.]
   [ 89. 154. 212.]
   [ 88. 153. 211.]
   ...
   [ 48. 114. 175.]
   [ 48. 114. 175.]
   [ 48. 114. 175.]]

  ...

  [[160. 134. 111.]
   [166. 143. 135.]
   [174. 158. 145.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[161. 128. 111.]
   [167. 143. 131.]
   [167. 154. 135.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]

  [[156. 118. 105.]
   [164. 136. 122.]
   [160. 149. 121.]
   ...
   [  0.   0.   0.]
   [  0.   0.   0.]
   [  0.   0.   0.]]]]


'\nThe first step is to load an image using image.load_img() and then convert it to a\narray. Next, an instance of ImageDataGenerator is created with several augmentation\nparame Finally, datagen.flow() is used to generate augmented images. The flow()method tak The for loop then iterates through the batches of augmented images\n# generated by flo\n# Overall, this code can be useful for generating additional training data for comput\n'